name: Branch build

on:
  push:
    branches-ignore:
      - main

jobs:

  python_tests:
    name: Execute resume tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          npm install -g resume-cli
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          python setup.py install

      - name: Validate resume schema
        run: resume validate

      - name: Run unit tests
        run: pytest

      - name: Converting JSON to Markdown
        run: |
          python ./resume/__main__.py --input 'resume.json' --output 'resume.md' --format 'markdown'

      - name: Check spelling
        uses: sbates130272/spellcheck-github-actions@v0.6.0

      - name: Verify URLs
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-path: ./resume.md


  convert_resume:
    name: Generate resume files
    runs-on: ubuntu-latest
    needs: python_tests

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup
        run: |
          npm install -g resume-cli
          npm install jsonresume-theme-even
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install
          mkdir output

      - name: JSON -> HTML
        run: resume export output/resume.html --format html

      - name: JSON -> PDF
        run: resume export output/resume.pdf --format pdf

      - name: JSON -> MarkDown
        run:  python ./resume/__main__.py --input 'resume.json' --output 'output/resume.md' --format 'markdown'

      - name: JSON -> XML (Generating)
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: json-to-xml
        with:
          path: 'resume.json'
          from: 'json'
          to: 'xml'

      - name: JSON -> XML (Write to file)
        run: echo "${{ steps.json-to-xml.outputs.data }}" >> output/resume.xml

      - name: JSON -> YAML
        run:  python ./resume/__main__.py --input 'resume.json' --output 'output/resume.yml' --format 'yaml'

      - name: Markdown -> TXT
        run: echo "TODO" # TODO

      - name: JSON -> DOCX
        run: echo "TODO" # TODO

      - name: Generate artifacts
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: output