name: Branch build

on:
  push:
    branches-ignore:
      - main

jobs:

  python_tests:
    name: Execute Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python setup.py install
          pytest

  convert_resume:
    name: Convert resume
    runs-on: ubuntu-latest
    needs: python_tests

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12

      - name: Setup
        run: |
          npm install -g resume-cli
          mkdir output

      - name: Verify JSON schema
        run: resume validate

      - name: Generate HTML resume
        run: resume export output/resume.html --format html

      - name: Generate PDF resume
        run: resume export output/resume.pdf --format pdf

#      - name: Generate XML resume
#        uses: fabasoad/yaml-json-xml-converter-action@main
#        id: json-to-xml
#        with:
#          path: 'resume.json'
#          from: 'json'
#          to: 'xml'
#      - name: Print to XML file
#        run: echo "${{ steps.json-to-xml.outputs.data }}" >> output/resume.xml

      - name: Generate YAML resume
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: json-to-yaml
        with:
          path: 'resume.json'
          from: 'json'
          to: 'yaml'
      - name: Print to YAML file
        run: echo '${{ steps.json-to-yaml.outputs.data }}' >> output/resume.yml


##      - name: Check spelling
##        uses: sbates130272/spellcheck-github-actions@v0.6.0
##      
##      - name: Verify URLs
##        uses: gaurav-nelson/github-action-markdown-link-check@v1
##        with:
##          file-path: ./resume.md
##
##      - name: Markdown -> JSON
##        run: python md-to-json.py resume.md > ./output/resume.json
##
##      - name: Markdown -> HTML
##        uses: docker://pandoc/latex:2.9
##        with:
##          args: --include-in-header style.css
##            --output=output/resume.html
##            resume.md
##
##      - name: Markdown -> TXT
##        uses: docker://pandoc/latex:2.9
##        with:
##          args: --output=output/resume.txt
##            resume.md
##
##      - name: HTML -> PDF
##        run: weasyprint ./output/resume.html ./output/resume.pdf
##
##      - name: Install libreoffice
##        run: |
##          sudo add-apt-repository ppa:libreoffice/ppa
##          sudo apt-get update
##          sudo apt-get install libreoffice
##
##      - name: HTML -> DOCX
##        run: |
##          libreoffice --headless --convert-to "docx:Office Open XML Text" ./output/resume.html
##          mv resume.docx ./output/resume.docx
##
##      - name: Generate artifacts
##        uses: actions/upload-artifact@v2
##        with:
##          name: resume
##          path: output
##
##      - name: Verify number of PDF pages
##        run: sudo bash ./test/pdf-page-test.sh
