name: Branch build

on:
  push:
    branches-ignore:
      - main

jobs:
  convert_resume:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install weasyprint
          sudo add-apt-repository ppa:libreoffice/ppa
          sudo apt-get update
          sudo apt-get install libreoffice
          sudo apt-get install poppler-utils
          sudo apt-get install -y ispell
          mkdir output

      - name: Markdown -> txt
        uses: docker://pandoc/latex:2.9
        with:
          args:
            --output=output/resume.txt
            resume.md

      - name: Markdown -> HTML
        uses: docker://pandoc/latex:2.9
        with:
          args: --include-in-header style.css
            --output=output/resume.html
            resume.md

      - name: HTML -> DOCX
        run: |
          libreoffice --headless --convert-to "docx:Office Open XML Text" ./output/resume.html
          mv resume.docx ./output/resume.docx

      - name: HTML -> PDF
        run: weasyprint ./output/resume.html ./output/resume.pdf

      - name: Generate artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: output

      - name: Verify number of PDF pages
        run: |
          sudo bash ./test/pdf-page-test.sh
          ispell ./output/resume.txt