name: Release build

on:
  push:
    branches:
      - main

jobs:
  release_resume:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install weasyprint
          sudo apt-get install poppler-utils
          sudo apt-get install -y aspell
          mkdir output

      - name: Check spelling
        uses: sbates130272/spellcheck-github-actions@v0.6.0

      - name: Verify URLs
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-path: ./resume.md

      - name: Markdown -> JSON
        run: python md-to-json.py resume.md > ./output/resume.json

      - name: Markdown -> HTML
        uses: docker://pandoc/latex:2.9
        with:
          args: --include-in-header style.css
            --output=output/resume.html
            resume.md

      - name: Markdown -> TXT
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/resume.txt
            resume.md

      - name: HTML -> PDF
        run: weasyprint ./output/resume.html ./output/resume.pdf

      - name: Install libreoffice
        run: |
          sudo add-apt-repository ppa:libreoffice/ppa
          sudo apt-get update
          sudo apt-get install libreoffice

      - name: HTML -> DOCX
        run: |
          libreoffice --headless --convert-to "docx:Office Open XML Text" ./output/resume.html
          mv resume.docx ./output/resume.docx

      - name: Verify number of PDF pages
        run: sudo bash ./test/pdf-page-test.sh

      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          WITH_V: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_bump.outputs.tag  }}
          release_name: Resume - ${{ steps.version_bump.outputs.tag  }}
          draft: false
          prerelease: false

      - name: Upload PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf

      - name: Upload HTML
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/resume.html
          asset_name: resume.html
          asset_content_type: text/html

      - name: Upload DOCX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/resume.docx
          asset_name: resume.docx
          asset_content_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

      - name: Upload JSON
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/resume.json
          asset_name: resume.json
          asset_content_type: application/json

      - name: Upload TXT
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/resume.txt
          asset_name: resume.txt
          asset_content_type: application/text

      - name: Copy HTML file to public
        run: |
          mkdir public
          cp ./output/resume.html ./public/index.html
          cp ./output/resume.json ./public/resume.json
          cp ./output/resume.txt ./public/resume.txt

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: github-page
