name: Compiling

on: push

jobs:
  convert_resume:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: 
            --include-in-header style.css 
            --output=output/resume.html resume.md
      - uses: docker://pandoc/latex:2.9
        with:
          args: 
            --template style.tex
            --variable papersize=A4
            --output=output/resume.pdf resume.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output