name: Compiling

on: push

jobs:
  convert_resume:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install weasyprint
          mkdir output

      - name: Markdown to HTML
        uses: docker://pandoc/latex:2.9
        with:
          args: --include-in-header style.css
            --output=output/resume.html
            resume.md

      - name: HTML to PDF
        run: weasyprint ./output/resume.html ./output/resume.pdf

      - name: Publish
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
