name: Release build

on:
  push:
    branches:
      - main

jobs:
  release_resume:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install weasyprint
          sudo add-apt-repository ppa:libreoffice/ppa
          sudo apt-get update
          sudo apt-get install libreoffice
          mkdir output

      - name: Markdown -> HTML
        uses: docker://pandoc/latex:2.9
        with:
          args: --include-in-header style.css
            --output=output/resume.html
            resume.md

      - name: HTML -> DOCX
        run: |
          libreoffice --headless --convert-to "docx:Office Open XML Text" ./output/resume.html
          mv resume.docx ./output/resume.docx

      - name: HTML -> PDF
        run: weasyprint ./output/resume.html ./output/resume.pdf

      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          WITH_V: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_bump.outputs.tag  }}
          release_name: Resume - ${{ steps.version_bump.outputs.tag  }}
          draft: false
          prerelease: false

      - name: Upload PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf

      - name: Upload HTML
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/resume.html
          asset_name: resume.html
          asset_content_type: text/html

      - name: Upload DOCX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/resume.docx
          asset_name: resume.docx
          asset_content_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

      - name: Copy HTML file to public
        run: |
          mkdir public
          cp ./output/resume.html ./public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: github-page 
